### ISSUE TITLE
Why not migration to tensorflow/addons?

### ISSUE THREAD

**Issue by ogencoglu** [eliorc/tavolo#11]
Thanks for the nice work!

Why not merging this with tensorflow/addons (https://github.com/tensorflow/addons) which contains several similar plug-and-play functionalities?

**Comment by eliorc** [comment]
Quite a similar question to why PyTorch did not contribute to TensorFlow

tavolo started as a personal tool, and has its style (like shape comments etc.), when I viewed the addon's project (which is very wide and quite amazing to be honest) in the thought of contributing I decided to keep this project separable.

Obviously, the projects are not mutually exclusive and can be used together... To conclude I did think about it and decided not to do so.

Hope this answers your question
